apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    # when building image, don't push to docker hub
    #local:
        #push: false
    googleCloudBuild:
        projectId: collecttiks
    artifacts:
        #- image: gcr.io/collecttiks/auth
        - image: zgoksu/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        #- image: gcr.io/collecttiks/client
        - image: zgoksu/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
        #- image: gcr.io/collecttiks/tickets
        - image: zgoksu/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        #- image: gcr.io/collecttiks/orders
        - image: zgoksu/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
