apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    # when building image, don't push to docker hub
    local:
        push: false
    artifacts:
        - image: zgoksu/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
